# Generated by Django 5.1.2 on 2025-05-04 06:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_counselor', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
