# Generated by Django 5.2 on 2025-05-03 19:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forumpost",
            options={},
        ),
        migrations.AlterModelOptions(
            name="forumreply",
            options={},
        ),
    ]
